insert into ZONA_GEOGRAFICA values(1000,'DEPARTAMENTOS',null);
--update ZONA_GEOGRAFICA set id_padre = 1000 where id_padre  is null;

insert into ZONA_GEOGRAFICA values(05,'ANTIOQUIA',1000);
insert into ZONA_GEOGRAFICA values(08,'ATLANTICO',1000);
insert into ZONA_GEOGRAFICA values(11,'BOGOTA',1000);
insert into ZONA_GEOGRAFICA values(13,'BOLIVAR',1000);
insert into ZONA_GEOGRAFICA values(15,'BOYACA',1000);
insert into ZONA_GEOGRAFICA values(17,'CALDAS',1000);
insert into ZONA_GEOGRAFICA values(18,'CAQUETA',1000);
insert into ZONA_GEOGRAFICA values(19,'CAUCA',1000);
insert into ZONA_GEOGRAFICA values(20,'CESAR',1000);
insert into ZONA_GEOGRAFICA values(23,'CORDOBA',1000);
insert into ZONA_GEOGRAFICA values(25,'CUNDINAMARCA',1000);
insert into ZONA_GEOGRAFICA values(27,'CHOCO',1000);
insert into ZONA_GEOGRAFICA values(41,'HUILA',1000);
insert into ZONA_GEOGRAFICA values(44,'LA GUAJIRA',1000);
insert into ZONA_GEOGRAFICA values(47,'MAGDALENA',1000);
insert into ZONA_GEOGRAFICA values(50,'META',1000);
insert into ZONA_GEOGRAFICA values(52,'NARIÑO',1000);
insert into ZONA_GEOGRAFICA values(54,'N. DE SANTANDER',1000);
insert into ZONA_GEOGRAFICA values(63,'QUINDIO',1000);
insert into ZONA_GEOGRAFICA values(66,'RISARALDA',1000);
insert into ZONA_GEOGRAFICA values(68,'SANTANDER',1000);
insert into ZONA_GEOGRAFICA values(70,'SUCRE',1000);
insert into ZONA_GEOGRAFICA values(73,'TOLIMA',1000);
insert into ZONA_GEOGRAFICA values(76,'VALLE DEL CAUCA',1000);
insert into ZONA_GEOGRAFICA values(81,'ARAUCA',1000);
insert into ZONA_GEOGRAFICA values(85,'CASANARE',1000);
insert into ZONA_GEOGRAFICA values(86,'PUTUMAYO',1000);
insert into ZONA_GEOGRAFICA values(88,'SAN ANDRES',1000);
insert into ZONA_GEOGRAFICA values(91,'AMAZONAS',1000);
insert into ZONA_GEOGRAFICA values(94,'GUAINIA',1000);
insert into ZONA_GEOGRAFICA values(95,'GUAVIARE',1000);
insert into ZONA_GEOGRAFICA values(97,'VAUPES',1000);
insert into ZONA_GEOGRAFICA values(99,'VICHADA',1000);
--//departamentos fin

insert into ZONA_GEOGRAFICA values(1001,'BARRANQUILLA',08);
insert into ZONA_GEOGRAFICA values(1002,'BOGOTA, D.C.',11);
insert into ZONA_GEOGRAFICA values(1003,'CARTAGENA',13);
insert into ZONA_GEOGRAFICA values(1004,'TUNJA',15);
insert into ZONA_GEOGRAFICA values(1005,'MANIZALES',17);
insert into ZONA_GEOGRAFICA values(1006,'FLORENCIA',18);
insert into ZONA_GEOGRAFICA values(1007,'POPAYAN',19);
insert into ZONA_GEOGRAFICA values(1008,'VALLEDUPAR',20);
insert into ZONA_GEOGRAFICA values(1009,'MONTERIA',23);
insert into ZONA_GEOGRAFICA values(1010,'AGUA DE DIOS',25);
insert into ZONA_GEOGRAFICA values(1011,'QUIBDO',27);
insert into ZONA_GEOGRAFICA values(1012,'NEIVA',41);
insert into ZONA_GEOGRAFICA values(1013,'RIOHACHA',44);
insert into ZONA_GEOGRAFICA values(1014,'SANTA MARTA',47);
insert into ZONA_GEOGRAFICA values(1015,'VILLAVICENCIO',50);
insert into ZONA_GEOGRAFICA values(1016,'PASTO',52);
insert into ZONA_GEOGRAFICA values(1017,'CUCUTA',54);
insert into ZONA_GEOGRAFICA values(1018,'ARMENIA',63);
insert into ZONA_GEOGRAFICA values(1019,'PEREIRA',66);
insert into ZONA_GEOGRAFICA values(1020,'BUCARAMANGA',68);
insert into ZONA_GEOGRAFICA values(1021,'SINCELEJO',70);
insert into ZONA_GEOGRAFICA values(1022,'IBAGUE',73);
insert into ZONA_GEOGRAFICA values(1023,'CALI',76);
insert into ZONA_GEOGRAFICA values(1024,'ARAUCA',81);
insert into ZONA_GEOGRAFICA values(1025,'YOPAL',85);
insert into ZONA_GEOGRAFICA values(1026,'MOCOA',86);
insert into ZONA_GEOGRAFICA values(1027,'SAN ANDRES',88);
insert into ZONA_GEOGRAFICA values(1028,'INIRIDA',94);
insert into ZONA_GEOGRAFICA values(1029,'MITU',97);
insert into ZONA_GEOGRAFICA values(1030,'PUERTO CARREÑO',99);


insert into ZONA_GEOGRAFICA values(001,'MEDELLIN',05);
insert into ZONA_GEOGRAFICA values(002,'ABEJORRAL',05);
insert into ZONA_GEOGRAFICA values(004,'ABRIAQUI',05);
insert into ZONA_GEOGRAFICA values(021,'ALEJANDRIA',05);
insert into ZONA_GEOGRAFICA values(030,'AMAGA',05);
insert into ZONA_GEOGRAFICA values(031,'AMALFI',05);
insert into ZONA_GEOGRAFICA values(034,'ANDES',05);
insert into ZONA_GEOGRAFICA values(036,'ANGELOPOLIS',05);
insert into ZONA_GEOGRAFICA values(038,'ANGOSTURA',05);
insert into ZONA_GEOGRAFICA values(040,'ANORI',05);
insert into ZONA_GEOGRAFICA values(042,'SANTAFE DE ANTIOQUIA',05);
insert into ZONA_GEOGRAFICA values(044,'ANZA',05);
insert into ZONA_GEOGRAFICA values(045,'APARTADO',05);
insert into ZONA_GEOGRAFICA values(051,'ARBOLETES',05);
insert into ZONA_GEOGRAFICA values(055,'ARGELIA',05);
insert into ZONA_GEOGRAFICA values(059,'ARMENIA',05);
insert into ZONA_GEOGRAFICA values(079,'BARBOSA',05);
insert into ZONA_GEOGRAFICA values(086,'BELMIRA',05);
insert into ZONA_GEOGRAFICA values(088,'BELLO',05);
insert into ZONA_GEOGRAFICA values(091,'BETANIA',05);
insert into ZONA_GEOGRAFICA values(093,'BETULIA',05);
insert into ZONA_GEOGRAFICA values(101,'CIUDAD BOLIVAR',05);
insert into ZONA_GEOGRAFICA values(107,'BRICEÑO',05);
insert into ZONA_GEOGRAFICA values(113,'BURITICA',05);
insert into ZONA_GEOGRAFICA values(120,'CACERES',05);
insert into ZONA_GEOGRAFICA values(125,'CAICEDO',05);
insert into ZONA_GEOGRAFICA values(129,'CALDAS',05);
insert into ZONA_GEOGRAFICA values(134,'CAMPAMENTO',05);
insert into ZONA_GEOGRAFICA values(138,'CAÑASGORDAS',05);
insert into ZONA_GEOGRAFICA values(142,'CARACOLI',05);
insert into ZONA_GEOGRAFICA values(145,'CARAMANTA',05);
insert into ZONA_GEOGRAFICA values(147,'CAREPA',05);
insert into ZONA_GEOGRAFICA values(148,'EL CARMEN DE VIBORAL',05);
insert into ZONA_GEOGRAFICA values(150,'CAROLINA',05);
insert into ZONA_GEOGRAFICA values(154,'CAUCASIA',05);
insert into ZONA_GEOGRAFICA values(172,'CHIGORODO',05);
insert into ZONA_GEOGRAFICA values(190,'CISNEROS',05);
insert into ZONA_GEOGRAFICA values(197,'COCORNA',05);
insert into ZONA_GEOGRAFICA values(206,'CONCEPCION',05);
insert into ZONA_GEOGRAFICA values(209,'CONCORDIA',05);
insert into ZONA_GEOGRAFICA values(212,'COPACABANA',05);
insert into ZONA_GEOGRAFICA values(234,'DABEIBA',05);
insert into ZONA_GEOGRAFICA values(237,'DON MATIAS',05);
insert into ZONA_GEOGRAFICA values(240,'EBEJICO',05);
insert into ZONA_GEOGRAFICA values(250,'EL BAGRE',05);
insert into ZONA_GEOGRAFICA values(264,'ENTRERRIOS',05);
insert into ZONA_GEOGRAFICA values(266,'ENVIGADO',05);
insert into ZONA_GEOGRAFICA values(282,'FREDONIA',05);
insert into ZONA_GEOGRAFICA values(284,'FRONTINO',05);
insert into ZONA_GEOGRAFICA values(306,'GIRALDO',05);
insert into ZONA_GEOGRAFICA values(308,'GIRARDOTA',05);
insert into ZONA_GEOGRAFICA values(310,'GOMEZ PLATA',05);
insert into ZONA_GEOGRAFICA values(313,'GRANADA',05);
insert into ZONA_GEOGRAFICA values(315,'GUADALUPE',05);
insert into ZONA_GEOGRAFICA values(318,'GUARNE',05);
insert into ZONA_GEOGRAFICA values(321,'GUATAPE',05);
insert into ZONA_GEOGRAFICA values(347,'HELICONIA',05);
insert into ZONA_GEOGRAFICA values(353,'HISPANIA',05);
insert into ZONA_GEOGRAFICA values(360,'ITAGUI',05);
insert into ZONA_GEOGRAFICA values(361,'ITUANGO',05);
insert into ZONA_GEOGRAFICA values(364,'JARDIN',05);
insert into ZONA_GEOGRAFICA values(368,'JERICO',05);
insert into ZONA_GEOGRAFICA values(376,'LA CEJA',05);
insert into ZONA_GEOGRAFICA values(380,'LA ESTRELLA',05);
insert into ZONA_GEOGRAFICA values(390,'LA PINTADA',05);
insert into ZONA_GEOGRAFICA values(400,'LA UNION',05);
insert into ZONA_GEOGRAFICA values(411,'LIBORINA',05);
insert into ZONA_GEOGRAFICA values(425,'MACEO',05);
insert into ZONA_GEOGRAFICA values(440,'MARINILLA',05);
insert into ZONA_GEOGRAFICA values(467,'MONTEBELLO',05);
insert into ZONA_GEOGRAFICA values(475,'MURINDO',05);
insert into ZONA_GEOGRAFICA values(480,'MUTATA',05);
insert into ZONA_GEOGRAFICA values(483,'NARIÑO',05);
insert into ZONA_GEOGRAFICA values(490,'NECOCLI',05);
insert into ZONA_GEOGRAFICA values(495,'NECHI',05);
insert into ZONA_GEOGRAFICA values(501,'OLAYA',05);
insert into ZONA_GEOGRAFICA values(541,'PEÐOL',05);
insert into ZONA_GEOGRAFICA values(543,'PEQUE',05);
insert into ZONA_GEOGRAFICA values(576,'PUEBLORRICO',05);
insert into ZONA_GEOGRAFICA values(579,'PUERTO BERRIO',05);
insert into ZONA_GEOGRAFICA values(585,'PUERTO NARE',05);
insert into ZONA_GEOGRAFICA values(591,'PUERTO TRIUNFO',05);
insert into ZONA_GEOGRAFICA values(604,'REMEDIOS',05);
insert into ZONA_GEOGRAFICA values(607,'RETIRO',05);
insert into ZONA_GEOGRAFICA values(615,'RIONEGRO',05);
insert into ZONA_GEOGRAFICA values(628,'SABANALARGA',05);
insert into ZONA_GEOGRAFICA values(631,'SABANETA',05);
insert into ZONA_GEOGRAFICA values(642,'SALGAR',05);
insert into ZONA_GEOGRAFICA values(647,'SAN ANDRES DE CUERQUIA',05);
insert into ZONA_GEOGRAFICA values(649,'SAN CARLOS',05);
insert into ZONA_GEOGRAFICA values(652,'SAN FRANCISCO',05);
insert into ZONA_GEOGRAFICA values(656,'SAN JERONIMO',05);
insert into ZONA_GEOGRAFICA values(658,'SAN JOSE DE LA MONTAÑA',05);
insert into ZONA_GEOGRAFICA values(659,'SAN JUAN DE URABA',05);
insert into ZONA_GEOGRAFICA values(660,'SAN LUIS',05);
insert into ZONA_GEOGRAFICA values(664,'SAN PEDRO',05);
insert into ZONA_GEOGRAFICA values(665,'SAN PEDRO DE URABA',05);
insert into ZONA_GEOGRAFICA values(667,'SAN RAFAEL',05);
insert into ZONA_GEOGRAFICA values(670,'SAN ROQUE',05);
insert into ZONA_GEOGRAFICA values(674,'SAN VICENTE',05);
insert into ZONA_GEOGRAFICA values(679,'SANTA BARBARA',05);
insert into ZONA_GEOGRAFICA values(686,'SANTA ROSA DE OSOS',05);
insert into ZONA_GEOGRAFICA values(690,'SANTO DOMINGO',05);
insert into ZONA_GEOGRAFICA values(697,'EL SANTUARIO',05);
insert into ZONA_GEOGRAFICA values(736,'SEGOVIA',05);
insert into ZONA_GEOGRAFICA values(756,'SONSON',05);
insert into ZONA_GEOGRAFICA values(761,'SOPETRAN',05);
insert into ZONA_GEOGRAFICA values(789,'TAMESIS',05);
insert into ZONA_GEOGRAFICA values(790,'TARAZA',05);
insert into ZONA_GEOGRAFICA values(792,'TARSO',05);
insert into ZONA_GEOGRAFICA values(809,'TITIRIBI',05);
insert into ZONA_GEOGRAFICA values(819,'TOLEDO',05);
insert into ZONA_GEOGRAFICA values(837,'TURBO',05);
insert into ZONA_GEOGRAFICA values(842,'URAMITA',05);
insert into ZONA_GEOGRAFICA values(847,'URRAO',05);
insert into ZONA_GEOGRAFICA values(854,'VALDIVIA',05);
insert into ZONA_GEOGRAFICA values(856,'VALPARAISO',05);
insert into ZONA_GEOGRAFICA values(858,'VEGACHI',05);
insert into ZONA_GEOGRAFICA values(861,'VENECIA',05);
insert into ZONA_GEOGRAFICA values(873,'VIGIA DEL FUERTE',05);
insert into ZONA_GEOGRAFICA values(885,'YALI',05);
insert into ZONA_GEOGRAFICA values(887,'YARUMAL',05);
insert into ZONA_GEOGRAFICA values(890,'YOLOMBO',05);
insert into ZONA_GEOGRAFICA values(893,'YONDO',05);
insert into ZONA_GEOGRAFICA values(895,'ZARAGOZA',05);

insert into ZONA_GEOGRAFICA values(078,'BARANOA',08);
insert into ZONA_GEOGRAFICA values(137,'CAMPO DE LA CRUZ',08);
insert into ZONA_GEOGRAFICA values(141,'CANDELARIA',08);
insert into ZONA_GEOGRAFICA values(296,'GALAPA',08);
insert into ZONA_GEOGRAFICA values(372,'JUAN DE ACOSTA',08);
insert into ZONA_GEOGRAFICA values(421,'LURUACO',08);
insert into ZONA_GEOGRAFICA values(433,'MALAMBO',08);
insert into ZONA_GEOGRAFICA values(436,'MANATI',08);
insert into ZONA_GEOGRAFICA values(520,'PALMAR DE VARELA',08);
insert into ZONA_GEOGRAFICA values(549,'PIOJO',08);
insert into ZONA_GEOGRAFICA values(558,'POLONUEVO',08);
insert into ZONA_GEOGRAFICA values(560,'PONEDERA',08);
insert into ZONA_GEOGRAFICA values(573,'PUERTO COLOMBIA',08);
insert into ZONA_GEOGRAFICA values(606,'REPELON',08);
insert into ZONA_GEOGRAFICA values(634,'SABANAGRANDE',08);
insert into ZONA_GEOGRAFICA values(638,'SABANALARGA',08);
insert into ZONA_GEOGRAFICA values(675,'SANTA LUCIA',08);
insert into ZONA_GEOGRAFICA values(685,'SANTO TOMAS',08);
insert into ZONA_GEOGRAFICA values(758,'SOLEDAD',08);
insert into ZONA_GEOGRAFICA values(770,'SUAN',08);
insert into ZONA_GEOGRAFICA values(832,'TUBARA',08);
insert into ZONA_GEOGRAFICA values(849,'USIACURI',08);

insert into ZONA_GEOGRAFICA values(006,'ACHI',13);
insert into ZONA_GEOGRAFICA values(030,'ALTOS DEL ROSARIO',13);
insert into ZONA_GEOGRAFICA values(042,'ARENAL',13);
insert into ZONA_GEOGRAFICA values(052,'ARJONA',13);
insert into ZONA_GEOGRAFICA values(062,'ARROYOHONDO',13);
insert into ZONA_GEOGRAFICA values(074,'BARRANCO DE LOBA',13);
insert into ZONA_GEOGRAFICA values(140,'CALAMAR',13);
insert into ZONA_GEOGRAFICA values(160,'CANTAGALLO',13);
insert into ZONA_GEOGRAFICA values(188,'CICUCO',13);
insert into ZONA_GEOGRAFICA values(212,'CORDOBA',13);
insert into ZONA_GEOGRAFICA values(222,'CLEMENCIA',13);
insert into ZONA_GEOGRAFICA values(244,'EL CARMEN DE BOLIVAR',13);
insert into ZONA_GEOGRAFICA values(248,'EL GUAMO',13);
insert into ZONA_GEOGRAFICA values(268,'EL PEÑON',13);
insert into ZONA_GEOGRAFICA values(300,'HATILLO DE LOBA',13);
insert into ZONA_GEOGRAFICA values(430,'MAGANGUE',13);
insert into ZONA_GEOGRAFICA values(433,'MAHATES',13);
insert into ZONA_GEOGRAFICA values(440,'MARGARITA',13);
insert into ZONA_GEOGRAFICA values(442,'MARIA LA BAJA',13);
insert into ZONA_GEOGRAFICA values(458,'MONTECRISTO',13);
insert into ZONA_GEOGRAFICA values(468,'MOMPOS',13);
insert into ZONA_GEOGRAFICA values(490,'NOROSI',13);
insert into ZONA_GEOGRAFICA values(473,'MORALES',13);
insert into ZONA_GEOGRAFICA values(549,'PINILLOS',13);
insert into ZONA_GEOGRAFICA values(580,'REGIDOR',13);
insert into ZONA_GEOGRAFICA values(600,'RIO VIEJO',13);
insert into ZONA_GEOGRAFICA values(620,'SAN CRISTOBAL',13);
insert into ZONA_GEOGRAFICA values(647,'SAN ESTANISLAO',13);
insert into ZONA_GEOGRAFICA values(650,'SAN FERNANDO',13);
insert into ZONA_GEOGRAFICA values(654,'SAN JACINTO',13);
insert into ZONA_GEOGRAFICA values(655,'SAN JACINTO DEL CAUCA',13);
insert into ZONA_GEOGRAFICA values(657,'SAN JUAN NEPOMUCENO',13);
insert into ZONA_GEOGRAFICA values(667,'SAN MARTIN DE LOBA',13);
insert into ZONA_GEOGRAFICA values(670,'SAN PABLO',13);
insert into ZONA_GEOGRAFICA values(673,'SANTA CATALINA',13);
insert into ZONA_GEOGRAFICA values(683,'SANTA ROSA',13);
insert into ZONA_GEOGRAFICA values(688,'SANTA ROSA DEL SUR',13);
insert into ZONA_GEOGRAFICA values(744,'SIMITI',13);
insert into ZONA_GEOGRAFICA values(760,'SOPLAVIENTO',13);
insert into ZONA_GEOGRAFICA values(780,'TALAIGUA NUEVO',13);
insert into ZONA_GEOGRAFICA values(810,'TIQUISIO',13);
insert into ZONA_GEOGRAFICA values(836,'TURBACO',13);
insert into ZONA_GEOGRAFICA values(838,'TURBANA',13);
insert into ZONA_GEOGRAFICA values(873,'VILLANUEVA',13);
insert into ZONA_GEOGRAFICA values(894,'ZAMBRANO',13);

insert into ZONA_GEOGRAFICA values(022,'ALMEIDA',15);
insert into ZONA_GEOGRAFICA values(047,'AQUITANIA',15);
insert into ZONA_GEOGRAFICA values(051,'ARCABUCO',15);
insert into ZONA_GEOGRAFICA values(087,'BELEN',15);
insert into ZONA_GEOGRAFICA values(090,'BERBEO',15);
insert into ZONA_GEOGRAFICA values(092,'BETEITIVA',15);
insert into ZONA_GEOGRAFICA values(097,'BOAVITA',15);
insert into ZONA_GEOGRAFICA values(104,'BOYACA',15);
insert into ZONA_GEOGRAFICA values(106,'BRICEÑO',15);
insert into ZONA_GEOGRAFICA values(109,'BUENAVISTA',15);
insert into ZONA_GEOGRAFICA values(114,'BUSBANZA',15);
insert into ZONA_GEOGRAFICA values(131,'CALDAS',15);
insert into ZONA_GEOGRAFICA values(135,'CAMPOHERMOSO',15);
insert into ZONA_GEOGRAFICA values(162,'CERINZA',15);
insert into ZONA_GEOGRAFICA values(172,'CHINAVITA',15);
insert into ZONA_GEOGRAFICA values(176,'CHIQUINQUIRA',15);
insert into ZONA_GEOGRAFICA values(180,'CHISCAS',15);
insert into ZONA_GEOGRAFICA values(183,'CHITA',15);
insert into ZONA_GEOGRAFICA values(185,'CHITARAQUE',15);
insert into ZONA_GEOGRAFICA values(187,'CHIVATA',15);
insert into ZONA_GEOGRAFICA values(189,'CIENEGA',15);
insert into ZONA_GEOGRAFICA values(204,'COMBITA',15);
insert into ZONA_GEOGRAFICA values(212,'COPER',15);
insert into ZONA_GEOGRAFICA values(215,'CORRALES',15);
insert into ZONA_GEOGRAFICA values(218,'COVARACHIA',15);
insert into ZONA_GEOGRAFICA values(223,'CUBARA',15);
insert into ZONA_GEOGRAFICA values(224,'CUCAITA',15);
insert into ZONA_GEOGRAFICA values(226,'CUITIVA',15);
insert into ZONA_GEOGRAFICA values(232,'CHIQUIZA',15);
insert into ZONA_GEOGRAFICA values(236,'CHIVOR',15);
insert into ZONA_GEOGRAFICA values(238,'DUITAMA',15);
insert into ZONA_GEOGRAFICA values(244,'EL COCUY',15);
insert into ZONA_GEOGRAFICA values(248,'EL ESPINO',15);
insert into ZONA_GEOGRAFICA values(272,'FIRAVITOBA',15);
insert into ZONA_GEOGRAFICA values(276,'FLORESTA',15);
insert into ZONA_GEOGRAFICA values(293,'GACHANTIVA',15);
insert into ZONA_GEOGRAFICA values(296,'GAMEZA',15);
insert into ZONA_GEOGRAFICA values(299,'GARAGOA',15);
insert into ZONA_GEOGRAFICA values(317,'GUACAMAYAS',15);
insert into ZONA_GEOGRAFICA values(322,'GUATEQUE',15);
insert into ZONA_GEOGRAFICA values(325,'GUAYATA',15);
insert into ZONA_GEOGRAFICA values(332,'GsICAN',15);
insert into ZONA_GEOGRAFICA values(362,'IZA',15);
insert into ZONA_GEOGRAFICA values(367,'JENESANO',15);
insert into ZONA_GEOGRAFICA values(368,'JERICO',15);
insert into ZONA_GEOGRAFICA values(377,'LABRANZAGRANDE',15);
insert into ZONA_GEOGRAFICA values(380,'LA CAPILLA',15);
insert into ZONA_GEOGRAFICA values(401,'LA VICTORIA',15);
insert into ZONA_GEOGRAFICA values(403,'LA UVITA',15);
insert into ZONA_GEOGRAFICA values(407,'VILLA DE LEYVA',15);
insert into ZONA_GEOGRAFICA values(425,'MACANAL',15);
insert into ZONA_GEOGRAFICA values(442,'MARIPI',15);
insert into ZONA_GEOGRAFICA values(455,'MIRAFLORES',15);
insert into ZONA_GEOGRAFICA values(464,'MONGUA',15);
insert into ZONA_GEOGRAFICA values(466,'MONGUI',15);
insert into ZONA_GEOGRAFICA values(469,'MONIQUIRA',15);
insert into ZONA_GEOGRAFICA values(476,'MOTAVITA',15);
insert into ZONA_GEOGRAFICA values(480,'MUZO',15);
insert into ZONA_GEOGRAFICA values(491,'NOBSA',15);
insert into ZONA_GEOGRAFICA values(494,'NUEVO COLON',15);
insert into ZONA_GEOGRAFICA values(500,'OICATA',15);
insert into ZONA_GEOGRAFICA values(507,'OTANCHE',15);
insert into ZONA_GEOGRAFICA values(511,'PACHAVITA',15);
insert into ZONA_GEOGRAFICA values(514,'PAEZ',15);
insert into ZONA_GEOGRAFICA values(516,'PAIPA',15);
insert into ZONA_GEOGRAFICA values(518,'PAJARITO',15);
insert into ZONA_GEOGRAFICA values(522,'PANQUEBA',15);
insert into ZONA_GEOGRAFICA values(531,'PAUNA',15);
insert into ZONA_GEOGRAFICA values(533,'PAYA',15);
insert into ZONA_GEOGRAFICA values(537,'PAZ DE RIO',15);
insert into ZONA_GEOGRAFICA values(542,'PESCA',15);
insert into ZONA_GEOGRAFICA values(550,'PISBA',15);
insert into ZONA_GEOGRAFICA values(572,'PUERTO BOYACA',15);
insert into ZONA_GEOGRAFICA values(580,'QUIPAMA',15);
insert into ZONA_GEOGRAFICA values(599,'RAMIRIQUI',15);
insert into ZONA_GEOGRAFICA values(600,'RAQUIRA',15);
insert into ZONA_GEOGRAFICA values(621,'RONDON',15);
insert into ZONA_GEOGRAFICA values(632,'SABOYA',15);
insert into ZONA_GEOGRAFICA values(638,'SACHICA',15);
insert into ZONA_GEOGRAFICA values(646,'SAMACA',15);
insert into ZONA_GEOGRAFICA values(660,'SAN EDUARDO',15);
insert into ZONA_GEOGRAFICA values(664,'SAN JOSE DE PARE',15);
insert into ZONA_GEOGRAFICA values(667,'SAN LUIS DE GACENO',15);
insert into ZONA_GEOGRAFICA values(673,'SAN MATEO',15);
insert into ZONA_GEOGRAFICA values(676,'SAN MIGUEL DE SEMA',15);
insert into ZONA_GEOGRAFICA values(681,'SAN PABLO DE BORBUR',15);
insert into ZONA_GEOGRAFICA values(686,'SANTANA',15);
insert into ZONA_GEOGRAFICA values(690,'SANTA MARIA',15);
insert into ZONA_GEOGRAFICA values(693,'SANTA ROSA DE VITERBO',15);
insert into ZONA_GEOGRAFICA values(696,'SANTA SOFIA',15);
insert into ZONA_GEOGRAFICA values(720,'SATIVANORTE',15);
insert into ZONA_GEOGRAFICA values(723,'SATIVASUR',15);
insert into ZONA_GEOGRAFICA values(740,'SIACHOQUE',15);
insert into ZONA_GEOGRAFICA values(753,'SOATA',15);
insert into ZONA_GEOGRAFICA values(755,'SOCOTA',15);
insert into ZONA_GEOGRAFICA values(757,'SOCHA',15);
insert into ZONA_GEOGRAFICA values(759,'SOGAMOSO',15);
insert into ZONA_GEOGRAFICA values(761,'SOMONDOCO',15);
insert into ZONA_GEOGRAFICA values(762,'SORA',15);
insert into ZONA_GEOGRAFICA values(763,'SOTAQUIRA',15);
insert into ZONA_GEOGRAFICA values(764,'SORACA',15);
insert into ZONA_GEOGRAFICA values(774,'SUSACON',15);
insert into ZONA_GEOGRAFICA values(776,'SUTAMARCHAN',15);
insert into ZONA_GEOGRAFICA values(778,'SUTATENZA',15);
insert into ZONA_GEOGRAFICA values(790,'TASCO',15);
insert into ZONA_GEOGRAFICA values(798,'TENZA',15);
insert into ZONA_GEOGRAFICA values(804,'TIBANA',15);
insert into ZONA_GEOGRAFICA values(806,'TIBASOSA',15);
insert into ZONA_GEOGRAFICA values(808,'TINJACA',15);
insert into ZONA_GEOGRAFICA values(810,'TIPACOQUE',15);
insert into ZONA_GEOGRAFICA values(814,'TOCA',15);
insert into ZONA_GEOGRAFICA values(816,'TOGsI',15);
insert into ZONA_GEOGRAFICA values(820,'TOPAGA',15);
insert into ZONA_GEOGRAFICA values(822,'TOTA',15);
insert into ZONA_GEOGRAFICA values(832,'TUNUNGUA',15);
insert into ZONA_GEOGRAFICA values(835,'TURMEQUE',15);
insert into ZONA_GEOGRAFICA values(837,'TUTA',15);
insert into ZONA_GEOGRAFICA values(839,'TUTAZA',15);
insert into ZONA_GEOGRAFICA values(842,'UMBITA',15);
insert into ZONA_GEOGRAFICA values(861,'VENTAQUEMADA',15);
insert into ZONA_GEOGRAFICA values(879,'VIRACACHA',15);
insert into ZONA_GEOGRAFICA values(897,'ZETAQUIRA',15);

insert into ZONA_GEOGRAFICA values(013,'AGUADAS',17);
insert into ZONA_GEOGRAFICA values(042,'ANSERMA',17);
insert into ZONA_GEOGRAFICA values(050,'ARANZAZU',17);
insert into ZONA_GEOGRAFICA values(088,'BELALCAZAR',17);
insert into ZONA_GEOGRAFICA values(174,'CHINCHINA',17);
insert into ZONA_GEOGRAFICA values(272,'FILADELFIA',17);
insert into ZONA_GEOGRAFICA values(380,'LA DORADA',17);
insert into ZONA_GEOGRAFICA values(388,'LA MERCED',17);
insert into ZONA_GEOGRAFICA values(433,'MANZANARES',17);
insert into ZONA_GEOGRAFICA values(442,'MARMATO',17);
insert into ZONA_GEOGRAFICA values(444,'MARQUETALIA',17);
insert into ZONA_GEOGRAFICA values(446,'MARULANDA',17);
insert into ZONA_GEOGRAFICA values(486,'NEIRA',17);
insert into ZONA_GEOGRAFICA values(495,'NORCASIA',17);
insert into ZONA_GEOGRAFICA values(513,'PACORA',17);
insert into ZONA_GEOGRAFICA values(524,'PALESTINA',17);
insert into ZONA_GEOGRAFICA values(541,'PENSILVANIA',17);
insert into ZONA_GEOGRAFICA values(614,'RIOSUCIO',17);
insert into ZONA_GEOGRAFICA values(616,'RISARALDA',17);
insert into ZONA_GEOGRAFICA values(653,'SALAMINA',17);
insert into ZONA_GEOGRAFICA values(662,'SAMANA',17);
insert into ZONA_GEOGRAFICA values(665,'SAN JOSE',17);
insert into ZONA_GEOGRAFICA values(777,'SUPIA',17);
insert into ZONA_GEOGRAFICA values(867,'VICTORIA',17);
insert into ZONA_GEOGRAFICA values(873,'VILLAMARIA',17);
insert into ZONA_GEOGRAFICA values(877,'VITERBO',17);

insert into ZONA_GEOGRAFICA values(029,'ALBANIA',18);
insert into ZONA_GEOGRAFICA values(094,'BELEN DE LOS ANDAQUIES',18);
insert into ZONA_GEOGRAFICA values(150,'CARTAGENA DEL CHAIRA',18);
insert into ZONA_GEOGRAFICA values(205,'CURILLO',18);
insert into ZONA_GEOGRAFICA values(247,'EL DONCELLO',18);
insert into ZONA_GEOGRAFICA values(256,'EL PAUJIL',18);
insert into ZONA_GEOGRAFICA values(410,'LA MONTAÑITA',18);
insert into ZONA_GEOGRAFICA values(460,'MILAN',18);
insert into ZONA_GEOGRAFICA values(479,'MORELIA',18);
insert into ZONA_GEOGRAFICA values(592,'PUERTO RICO',18);
insert into ZONA_GEOGRAFICA values(610,'SAN JOSE DEL FRAGUA',18);
insert into ZONA_GEOGRAFICA values(753,'SAN VICENTE DEL CAGUAN',18);
insert into ZONA_GEOGRAFICA values(756,'SOLANO',18);
insert into ZONA_GEOGRAFICA values(785,'SOLITA',18);
insert into ZONA_GEOGRAFICA values(860,'VALPARAISO',18);

insert into ZONA_GEOGRAFICA values(022,'ALMAGUER',19);
insert into ZONA_GEOGRAFICA values(050,'ARGELIA',19);
insert into ZONA_GEOGRAFICA values(075,'BALBOA',19);
insert into ZONA_GEOGRAFICA values(100,'BOLIVAR',19);
insert into ZONA_GEOGRAFICA values(110,'BUENOS AIRES',19);
insert into ZONA_GEOGRAFICA values(130,'CAJIBIO',19);
insert into ZONA_GEOGRAFICA values(137,'CALDONO',19);
insert into ZONA_GEOGRAFICA values(142,'CALOTO',19);
insert into ZONA_GEOGRAFICA values(212,'CORINTO',19);
insert into ZONA_GEOGRAFICA values(256,'EL TAMBO',19);
insert into ZONA_GEOGRAFICA values(290,'FLORENCIA',19);
insert into ZONA_GEOGRAFICA values(300,'GUACHENE',19);
insert into ZONA_GEOGRAFICA values(318,'GUAPI',19);
insert into ZONA_GEOGRAFICA values(355,'INZA',19);
insert into ZONA_GEOGRAFICA values(364,'JAMBALO',19);
insert into ZONA_GEOGRAFICA values(392,'LA SIERRA',19);
insert into ZONA_GEOGRAFICA values(397,'LA VEGA',19);
insert into ZONA_GEOGRAFICA values(418,'LOPEZ',19);
insert into ZONA_GEOGRAFICA values(450,'MERCADERES',19);
insert into ZONA_GEOGRAFICA values(455,'MIRANDA',19);
insert into ZONA_GEOGRAFICA values(473,'MORALES',19);
insert into ZONA_GEOGRAFICA values(513,'PADILLA',19);
insert into ZONA_GEOGRAFICA values(517,'PAEZ',19);
insert into ZONA_GEOGRAFICA values(532,'PATIA',19);
insert into ZONA_GEOGRAFICA values(533,'PIAMONTE',19);
insert into ZONA_GEOGRAFICA values(548,'PIENDAMO',19);
insert into ZONA_GEOGRAFICA values(573,'PUERTO TEJADA',19);
insert into ZONA_GEOGRAFICA values(585,'PURACE',19);
insert into ZONA_GEOGRAFICA values(622,'ROSAS',19);
insert into ZONA_GEOGRAFICA values(693,'SAN SEBASTIAN',19);
insert into ZONA_GEOGRAFICA values(698,'SANTANDER DE QUILICHAO',19);
insert into ZONA_GEOGRAFICA values(701,'SANTA ROSA',19);
insert into ZONA_GEOGRAFICA values(743,'SILVIA',19);
insert into ZONA_GEOGRAFICA values(760,'SOTARA',19);
insert into ZONA_GEOGRAFICA values(780,'SUAREZ',19);
insert into ZONA_GEOGRAFICA values(785,'SUCRE',19);
insert into ZONA_GEOGRAFICA values(807,'TIMBIO',19);
insert into ZONA_GEOGRAFICA values(809,'TIMBIQUI',19);
insert into ZONA_GEOGRAFICA values(821,'TORIBIO',19);
insert into ZONA_GEOGRAFICA values(824,'TOTORO',19);
insert into ZONA_GEOGRAFICA values(845,'VILLA RICA',19);

insert into ZONA_GEOGRAFICA values(011,'AGUACHICA',20);
insert into ZONA_GEOGRAFICA values(013,'AGUSTIN CODAZZI',20);
insert into ZONA_GEOGRAFICA values(032,'ASTREA',20);
insert into ZONA_GEOGRAFICA values(045,'BECERRIL',20);
insert into ZONA_GEOGRAFICA values(060,'BOSCONIA',20);
insert into ZONA_GEOGRAFICA values(175,'CHIMICHAGUA',20);
insert into ZONA_GEOGRAFICA values(178,'CHIRIGUANA',20);
insert into ZONA_GEOGRAFICA values(228,'CURUMANI',20);
insert into ZONA_GEOGRAFICA values(238,'EL COPEY',20);
insert into ZONA_GEOGRAFICA values(250,'EL PASO',20);
insert into ZONA_GEOGRAFICA values(295,'GAMARRA',20);
insert into ZONA_GEOGRAFICA values(310,'GONZALEZ',20);
insert into ZONA_GEOGRAFICA values(383,'LA GLORIA',20);
insert into ZONA_GEOGRAFICA values(400,'LA JAGUA DE IBIRICO',20);
insert into ZONA_GEOGRAFICA values(443,'MANAURE',20);
insert into ZONA_GEOGRAFICA values(517,'PAILITAS',20);
insert into ZONA_GEOGRAFICA values(550,'PELAYA',20);
insert into ZONA_GEOGRAFICA values(570,'PUEBLO BELLO',20);
insert into ZONA_GEOGRAFICA values(614,'RIO DE ORO',20);
insert into ZONA_GEOGRAFICA values(621,'LA PAZ',20);
insert into ZONA_GEOGRAFICA values(710,'SAN ALBERTO',20);
insert into ZONA_GEOGRAFICA values(750,'SAN DIEGO',20);
insert into ZONA_GEOGRAFICA values(770,'SAN MARTIN',20);
insert into ZONA_GEOGRAFICA values(787,'TAMALAMEQUE',20);

insert into ZONA_GEOGRAFICA values(068,'AYAPEL',23);
insert into ZONA_GEOGRAFICA values(079,'BUENAVISTA',23);
insert into ZONA_GEOGRAFICA values(090,'CANALETE',23);
insert into ZONA_GEOGRAFICA values(162,'CERETE',23);
insert into ZONA_GEOGRAFICA values(168,'CHIMA',23);
insert into ZONA_GEOGRAFICA values(182,'CHINU',23);
insert into ZONA_GEOGRAFICA values(189,'CIENAGA DE ORO',23);
insert into ZONA_GEOGRAFICA values(300,'COTORRA',23);
insert into ZONA_GEOGRAFICA values(350,'LA APARTADA',23);
insert into ZONA_GEOGRAFICA values(417,'LORICA',23);
insert into ZONA_GEOGRAFICA values(419,'LOS CORDOBAS',23);
insert into ZONA_GEOGRAFICA values(464,'MOMIL',23);
insert into ZONA_GEOGRAFICA values(466,'MONTELIBANO',23);
insert into ZONA_GEOGRAFICA values(500,'MOÑITOS',23);
insert into ZONA_GEOGRAFICA values(555,'PLANETA RICA',23);
insert into ZONA_GEOGRAFICA values(570,'PUEBLO NUEVO',23);
insert into ZONA_GEOGRAFICA values(574,'PUERTO ESCONDIDO',23);
insert into ZONA_GEOGRAFICA values(580,'PUERTO LIBERTADOR',23);
insert into ZONA_GEOGRAFICA values(586,'PURISIMA',23);
insert into ZONA_GEOGRAFICA values(660,'SAHAGUN',23);
insert into ZONA_GEOGRAFICA values(670,'SAN ANDRES SOTAVENTO',23);
insert into ZONA_GEOGRAFICA values(672,'SAN ANTERO',23);
insert into ZONA_GEOGRAFICA values(675,'SAN BERNARDO DEL VIENTO',23);
insert into ZONA_GEOGRAFICA values(678,'SAN CARLOS',23);
insert into ZONA_GEOGRAFICA values(686,'SAN PELAYO',23);
insert into ZONA_GEOGRAFICA values(807,'TIERRALTA',23);
insert into ZONA_GEOGRAFICA values(855,'VALENCIA',23);

insert into ZONA_GEOGRAFICA values(019,'ALBAN',25);
insert into ZONA_GEOGRAFICA values(035,'ANAPOIMA',25);
insert into ZONA_GEOGRAFICA values(040,'ANOLAIMA',25);
insert into ZONA_GEOGRAFICA values(053,'ARBELAEZ',25);
insert into ZONA_GEOGRAFICA values(086,'BELTRAN',25);
insert into ZONA_GEOGRAFICA values(095,'BITUIMA',25);
insert into ZONA_GEOGRAFICA values(099,'BOJACA',25);
insert into ZONA_GEOGRAFICA values(120,'CABRERA',25);
insert into ZONA_GEOGRAFICA values(123,'CACHIPAY',25);
insert into ZONA_GEOGRAFICA values(126,'CAJICA',25);
insert into ZONA_GEOGRAFICA values(148,'CAPARRAPI',25);
insert into ZONA_GEOGRAFICA values(151,'CAQUEZA',25);
insert into ZONA_GEOGRAFICA values(154,'CARMEN DE CARUPA',25);
insert into ZONA_GEOGRAFICA values(168,'CHAGUANI',25);
insert into ZONA_GEOGRAFICA values(175,'CHIA',25);
insert into ZONA_GEOGRAFICA values(178,'CHIPAQUE',25);
insert into ZONA_GEOGRAFICA values(181,'CHOACHI',25);
insert into ZONA_GEOGRAFICA values(183,'CHOCONTA',25);
insert into ZONA_GEOGRAFICA values(200,'COGUA',25);
insert into ZONA_GEOGRAFICA values(214,'COTA',25);
insert into ZONA_GEOGRAFICA values(224,'CUCUNUBA',25);
insert into ZONA_GEOGRAFICA values(245,'EL COLEGIO',25);
insert into ZONA_GEOGRAFICA values(258,'EL PEÑON',25);
insert into ZONA_GEOGRAFICA values(260,'EL ROSAL',25);
insert into ZONA_GEOGRAFICA values(269,'FACATATIVA',25);
insert into ZONA_GEOGRAFICA values(279,'FOMEQUE',25);
insert into ZONA_GEOGRAFICA values(281,'FOSCA',25);
insert into ZONA_GEOGRAFICA values(286,'FUNZA',25);
insert into ZONA_GEOGRAFICA values(288,'FUQUENE',25);
insert into ZONA_GEOGRAFICA values(290,'FUSAGASUGA',25);
insert into ZONA_GEOGRAFICA values(293,'GACHALA',25);
insert into ZONA_GEOGRAFICA values(295,'GACHANCIPA',25);
insert into ZONA_GEOGRAFICA values(297,'GACHETA',25);
insert into ZONA_GEOGRAFICA values(299,'GAMA',25);
insert into ZONA_GEOGRAFICA values(307,'GIRARDOT',25);
insert into ZONA_GEOGRAFICA values(312,'GRANADA',25);
insert into ZONA_GEOGRAFICA values(317,'GUACHETA',25);
insert into ZONA_GEOGRAFICA values(320,'GUADUAS',25);
insert into ZONA_GEOGRAFICA values(322,'GUASCA',25);
insert into ZONA_GEOGRAFICA values(324,'GUATAQUI',25);
insert into ZONA_GEOGRAFICA values(326,'GUATAVITA',25);
insert into ZONA_GEOGRAFICA values(328,'GUAYABAL DE SIQUIMA',25);
insert into ZONA_GEOGRAFICA values(335,'GUAYABETAL',25);
insert into ZONA_GEOGRAFICA values(339,'GUTIERREZ',25);
insert into ZONA_GEOGRAFICA values(368,'JERUSALEN',25);
insert into ZONA_GEOGRAFICA values(372,'JUNIN',25);
insert into ZONA_GEOGRAFICA values(377,'LA CALERA',25);
insert into ZONA_GEOGRAFICA values(386,'LA MESA',25);
insert into ZONA_GEOGRAFICA values(394,'LA PALMA',25);
insert into ZONA_GEOGRAFICA values(398,'LA PEÑA',25);
insert into ZONA_GEOGRAFICA values(402,'LA VEGA',25);
insert into ZONA_GEOGRAFICA values(407,'LENGUAZAQUE',25);
insert into ZONA_GEOGRAFICA values(426,'MACHETA',25);
insert into ZONA_GEOGRAFICA values(430,'MADRID',25);
insert into ZONA_GEOGRAFICA values(436,'MANTA',25);
insert into ZONA_GEOGRAFICA values(438,'MEDINA',25);
insert into ZONA_GEOGRAFICA values(473,'MOSQUERA',25);
insert into ZONA_GEOGRAFICA values(483,'NARIÑO',25);
insert into ZONA_GEOGRAFICA values(486,'NEMOCON',25);
insert into ZONA_GEOGRAFICA values(488,'NILO',25);
insert into ZONA_GEOGRAFICA values(489,'NIMAIMA',25);
insert into ZONA_GEOGRAFICA values(491,'NOCAIMA',25);
insert into ZONA_GEOGRAFICA values(506,'VENECIA',25);
insert into ZONA_GEOGRAFICA values(513,'PACHO',25);
insert into ZONA_GEOGRAFICA values(518,'PAIME',25);
insert into ZONA_GEOGRAFICA values(524,'PANDI',25);
insert into ZONA_GEOGRAFICA values(530,'PARATEBUENO',25);
insert into ZONA_GEOGRAFICA values(535,'PASCA',25);
insert into ZONA_GEOGRAFICA values(572,'PUERTO SALGAR',25);
insert into ZONA_GEOGRAFICA values(580,'PULI',25);
insert into ZONA_GEOGRAFICA values(592,'QUEBRADANEGRA',25);
insert into ZONA_GEOGRAFICA values(594,'QUETAME',25);
insert into ZONA_GEOGRAFICA values(596,'QUIPILE',25);
insert into ZONA_GEOGRAFICA values(599,'APULO',25);
insert into ZONA_GEOGRAFICA values(612,'RICAURTE',25);
insert into ZONA_GEOGRAFICA values(645,'SAN ANTONIO DEL TEQUENDAMA',25);
insert into ZONA_GEOGRAFICA values(649,'SAN BERNARDO',25);
insert into ZONA_GEOGRAFICA values(653,'SAN CAYETANO',25);
insert into ZONA_GEOGRAFICA values(658,'SAN FRANCISCO',25);
insert into ZONA_GEOGRAFICA values(662,'SAN JUAN DE RIO SECO',25);
insert into ZONA_GEOGRAFICA values(718,'SASAIMA',25);
insert into ZONA_GEOGRAFICA values(736,'SESQUILE',25);
insert into ZONA_GEOGRAFICA values(740,'SIBATE',25);
insert into ZONA_GEOGRAFICA values(743,'SILVANIA',25);
insert into ZONA_GEOGRAFICA values(745,'SIMIJACA',25);
insert into ZONA_GEOGRAFICA values(754,'SOACHA',25);
insert into ZONA_GEOGRAFICA values(758,'SOPO',25);
insert into ZONA_GEOGRAFICA values(769,'SUBACHOQUE',25);
insert into ZONA_GEOGRAFICA values(772,'SUESCA',25);
insert into ZONA_GEOGRAFICA values(777,'SUPATA',25);
insert into ZONA_GEOGRAFICA values(779,'SUSA',25);
insert into ZONA_GEOGRAFICA values(781,'SUTATAUSA',25);
insert into ZONA_GEOGRAFICA values(785,'TABIO',25);
insert into ZONA_GEOGRAFICA values(793,'TAUSA',25);
insert into ZONA_GEOGRAFICA values(797,'TENA',25);
insert into ZONA_GEOGRAFICA values(799,'TENJO',25);
insert into ZONA_GEOGRAFICA values(805,'TIBACUY',25);
insert into ZONA_GEOGRAFICA values(807,'TIBIRITA',25);
insert into ZONA_GEOGRAFICA values(815,'TOCAIMA',25);
insert into ZONA_GEOGRAFICA values(817,'TOCANCIPA',25);
insert into ZONA_GEOGRAFICA values(823,'TOPAIPI',25);
insert into ZONA_GEOGRAFICA values(839,'UBALA',25);
insert into ZONA_GEOGRAFICA values(841,'UBAQUE',25);
insert into ZONA_GEOGRAFICA values(843,'VILLA DE SAN DIEGO DE UBATE',25);
insert into ZONA_GEOGRAFICA values(845,'UNE',25);
insert into ZONA_GEOGRAFICA values(851,'UTICA',25);
insert into ZONA_GEOGRAFICA values(862,'VERGARA',25);
insert into ZONA_GEOGRAFICA values(867,'VIANI',25);
insert into ZONA_GEOGRAFICA values(871,'VILLAGOMEZ',25);
insert into ZONA_GEOGRAFICA values(873,'VILLAPINZON',25);
insert into ZONA_GEOGRAFICA values(875,'VILLETA',25);
insert into ZONA_GEOGRAFICA values(878,'VIOTA',25);
insert into ZONA_GEOGRAFICA values(885,'YACOPI',25);
insert into ZONA_GEOGRAFICA values(898,'ZIPACON',25);
insert into ZONA_GEOGRAFICA values(899,'ZIPAQUIRA',25);

insert into ZONA_GEOGRAFICA values(006,'ACANDI',27);
insert into ZONA_GEOGRAFICA values(025,'ALTO BAUDO',27);
insert into ZONA_GEOGRAFICA values(050,'ATRATO',27);
insert into ZONA_GEOGRAFICA values(073,'BAGADO',27);
insert into ZONA_GEOGRAFICA values(075,'BAHIA SOLANO',27);
insert into ZONA_GEOGRAFICA values(077,'BAJO BAUDO',27);
insert into ZONA_GEOGRAFICA values(099,'BOJAYA',27);
insert into ZONA_GEOGRAFICA values(135,'EL CANTON DEL SAN PABLO',27);
insert into ZONA_GEOGRAFICA values(150,'CARMEN DEL DARIEN',27);
insert into ZONA_GEOGRAFICA values(160,'CERTEGUI',27);
insert into ZONA_GEOGRAFICA values(205,'CONDOTO',27);
insert into ZONA_GEOGRAFICA values(245,'EL CARMEN DE ATRATO',27);
insert into ZONA_GEOGRAFICA values(250,'EL LITORAL DEL SAN JUAN',27);
insert into ZONA_GEOGRAFICA values(361,'ISTMINA',27);
insert into ZONA_GEOGRAFICA values(372,'JURADO',27);
insert into ZONA_GEOGRAFICA values(413,'LLORO',27);
insert into ZONA_GEOGRAFICA values(425,'MEDIO ATRATO',27);
insert into ZONA_GEOGRAFICA values(430,'MEDIO BAUDO',27);
insert into ZONA_GEOGRAFICA values(450,'MEDIO SAN JUAN',27);
insert into ZONA_GEOGRAFICA values(491,'NOVITA',27);
insert into ZONA_GEOGRAFICA values(495,'NUQUI',27);
insert into ZONA_GEOGRAFICA values(580,'RIO IRO',27);
insert into ZONA_GEOGRAFICA values(600,'RIO QUITO',27);
insert into ZONA_GEOGRAFICA values(615,'RIOSUCIO',27);
insert into ZONA_GEOGRAFICA values(660,'SAN JOSE DEL PALMAR',27);
insert into ZONA_GEOGRAFICA values(745,'SIPI',27);
insert into ZONA_GEOGRAFICA values(787,'TADO',27);
insert into ZONA_GEOGRAFICA values(800,'UNGUIA',27);
insert into ZONA_GEOGRAFICA values(810,'UNION PANAMERICANA',27);

insert into ZONA_GEOGRAFICA values(006,'ACEVEDO',41);
insert into ZONA_GEOGRAFICA values(013,'AGRADO',41);
insert into ZONA_GEOGRAFICA values(016,'AIPE',41);
insert into ZONA_GEOGRAFICA values(020,'ALGECIRAS',41);
insert into ZONA_GEOGRAFICA values(026,'ALTAMIRA',41);
insert into ZONA_GEOGRAFICA values(078,'BARAYA',41);
insert into ZONA_GEOGRAFICA values(132,'CAMPOALEGRE',41);
insert into ZONA_GEOGRAFICA values(206,'COLOMBIA',41);
insert into ZONA_GEOGRAFICA values(244,'ELIAS',41);
insert into ZONA_GEOGRAFICA values(298,'GARZON',41);
insert into ZONA_GEOGRAFICA values(306,'GIGANTE',41);
insert into ZONA_GEOGRAFICA values(319,'GUADALUPE',41);
insert into ZONA_GEOGRAFICA values(349,'HOBO',41);
insert into ZONA_GEOGRAFICA values(357,'IQUIRA',41);
insert into ZONA_GEOGRAFICA values(359,'ISNOS',41);
insert into ZONA_GEOGRAFICA values(378,'LA ARGENTINA',41);
insert into ZONA_GEOGRAFICA values(396,'LA PLATA',41);
insert into ZONA_GEOGRAFICA values(483,'NATAGA',41);
insert into ZONA_GEOGRAFICA values(503,'OPORAPA',41);
insert into ZONA_GEOGRAFICA values(518,'PAICOL',41);
insert into ZONA_GEOGRAFICA values(524,'PALERMO',41);
insert into ZONA_GEOGRAFICA values(530,'PALESTINA',41);
insert into ZONA_GEOGRAFICA values(548,'PITAL',41);
insert into ZONA_GEOGRAFICA values(551,'PITALITO',41);
insert into ZONA_GEOGRAFICA values(615,'RIVERA',41);
insert into ZONA_GEOGRAFICA values(660,'SALADOBLANCO',41);
insert into ZONA_GEOGRAFICA values(668,'SAN AGUSTIN',41);
insert into ZONA_GEOGRAFICA values(676,'SANTA MARIA',41);
insert into ZONA_GEOGRAFICA values(770,'SUAZA',41);
insert into ZONA_GEOGRAFICA values(791,'TARQUI',41);
insert into ZONA_GEOGRAFICA values(797,'TESALIA',41);
insert into ZONA_GEOGRAFICA values(799,'TELLO',41);
insert into ZONA_GEOGRAFICA values(801,'TERUEL',41);
insert into ZONA_GEOGRAFICA values(807,'TIMANA',41);
insert into ZONA_GEOGRAFICA values(872,'VILLAVIEJA',41);
insert into ZONA_GEOGRAFICA values(885,'YAGUARA',41);

insert into ZONA_GEOGRAFICA values(035,'ALBANIA',44);
insert into ZONA_GEOGRAFICA values(078,'BARRANCAS',44);
insert into ZONA_GEOGRAFICA values(090,'DIBULLA',44);
insert into ZONA_GEOGRAFICA values(098,'DISTRACCION',44);
insert into ZONA_GEOGRAFICA values(110,'EL MOLINO',44);
insert into ZONA_GEOGRAFICA values(279,'FONSECA',44);
insert into ZONA_GEOGRAFICA values(378,'HATONUEVO',44);
insert into ZONA_GEOGRAFICA values(420,'LA JAGUA DEL PILAR',44);
insert into ZONA_GEOGRAFICA values(430,'MAICAO',44);
insert into ZONA_GEOGRAFICA values(560,'MANAURE',44);
insert into ZONA_GEOGRAFICA values(650,'SAN JUAN DEL CESAR',44);
insert into ZONA_GEOGRAFICA values(847,'URIBIA',44);
insert into ZONA_GEOGRAFICA values(855,'URUMITA',44);
insert into ZONA_GEOGRAFICA values(874,'VILLANUEVA',44);

insert into ZONA_GEOGRAFICA values(030,'ALGARROBO',47);
insert into ZONA_GEOGRAFICA values(053,'ARACATACA',47);
insert into ZONA_GEOGRAFICA values(058,'ARIGUANI',47);
insert into ZONA_GEOGRAFICA values(161,'CERRO SAN ANTONIO',47);
insert into ZONA_GEOGRAFICA values(170,'CHIBOLO',47);
insert into ZONA_GEOGRAFICA values(189,'CIENAGA',47);
insert into ZONA_GEOGRAFICA values(205,'CONCORDIA',47);
insert into ZONA_GEOGRAFICA values(245,'EL BANCO',47);
insert into ZONA_GEOGRAFICA values(258,'EL PIÑON',47);
insert into ZONA_GEOGRAFICA values(268,'EL RETEN',47);
insert into ZONA_GEOGRAFICA values(288,'FUNDACION',47);
insert into ZONA_GEOGRAFICA values(318,'GUAMAL',47);
insert into ZONA_GEOGRAFICA values(460,'NUEVA GRANADA',47);
insert into ZONA_GEOGRAFICA values(541,'PEDRAZA',47);
insert into ZONA_GEOGRAFICA values(545,'PIJIÑO DEL CARMEN',47);
insert into ZONA_GEOGRAFICA values(551,'PIVIJAY',47);
insert into ZONA_GEOGRAFICA values(555,'PLATO',47);
insert into ZONA_GEOGRAFICA values(570,'PUEBLOVIEJO',47);
insert into ZONA_GEOGRAFICA values(605,'REMOLINO',47);
insert into ZONA_GEOGRAFICA values(660,'SABANAS DE SAN ANGEL',47);
insert into ZONA_GEOGRAFICA values(675,'SALAMINA',47);
insert into ZONA_GEOGRAFICA values(692,'SAN SEBASTIAN DE BUENAVISTA',47);
insert into ZONA_GEOGRAFICA values(703,'SAN ZENON',47);
insert into ZONA_GEOGRAFICA values(707,'SANTA ANA',47);
insert into ZONA_GEOGRAFICA values(720,'SANTA BARBARA DE PINTO',47);
insert into ZONA_GEOGRAFICA values(745,'SITIONUEVO',47);
insert into ZONA_GEOGRAFICA values(798,'TENERIFE',47);
insert into ZONA_GEOGRAFICA values(960,'ZAPAYAN',47);
insert into ZONA_GEOGRAFICA values(980,'ZONA BANANERA',47);

insert into ZONA_GEOGRAFICA values(006,'ACACIAS',50);
insert into ZONA_GEOGRAFICA values(110,'BARRANCA DE UPIA',50);
insert into ZONA_GEOGRAFICA values(124,'CABUYARO',50);
insert into ZONA_GEOGRAFICA values(150,'CASTILLA LA NUEVA',50);
insert into ZONA_GEOGRAFICA values(223,'CUBARRAL',50);
insert into ZONA_GEOGRAFICA values(226,'CUMARAL',50);
insert into ZONA_GEOGRAFICA values(245,'EL CALVARIO',50);
insert into ZONA_GEOGRAFICA values(251,'EL CASTILLO',50);
insert into ZONA_GEOGRAFICA values(270,'EL DORADO',50);
insert into ZONA_GEOGRAFICA values(287,'FUENTE DE ORO',50);
insert into ZONA_GEOGRAFICA values(313,'GRANADA',50);
insert into ZONA_GEOGRAFICA values(318,'GUAMAL',50);
insert into ZONA_GEOGRAFICA values(325,'MAPIRIPAN',50);
insert into ZONA_GEOGRAFICA values(330,'MESETAS',50);
insert into ZONA_GEOGRAFICA values(350,'LA MACARENA',50);
insert into ZONA_GEOGRAFICA values(370,'URIBE',50);
insert into ZONA_GEOGRAFICA values(400,'LEJANIAS',50);
insert into ZONA_GEOGRAFICA values(450,'PUERTO CONCORDIA',50);
insert into ZONA_GEOGRAFICA values(568,'PUERTO GAITAN',50);
insert into ZONA_GEOGRAFICA values(573,'PUERTO LOPEZ',50);
insert into ZONA_GEOGRAFICA values(577,'PUERTO LLERAS',50);
insert into ZONA_GEOGRAFICA values(590,'PUERTO RICO',50);
insert into ZONA_GEOGRAFICA values(606,'RESTREPO',50);
insert into ZONA_GEOGRAFICA values(680,'SAN CARLOS DE GUAROA',50);
insert into ZONA_GEOGRAFICA values(683,'SAN JUAN DE ARAMA',50);
insert into ZONA_GEOGRAFICA values(686,'SAN JUANITO',50);
insert into ZONA_GEOGRAFICA values(689,'SAN MARTIN',50);
insert into ZONA_GEOGRAFICA values(711,'VISTAHERMOSA',50);

insert into ZONA_GEOGRAFICA values(019,'ALBAN',52);
insert into ZONA_GEOGRAFICA values(022,'ALDANA',52);
insert into ZONA_GEOGRAFICA values(036,'ANCUYA',52);
insert into ZONA_GEOGRAFICA values(051,'ARBOLEDA',52);
insert into ZONA_GEOGRAFICA values(079,'BARBACOAS',52);
insert into ZONA_GEOGRAFICA values(083,'BELEN',52);
insert into ZONA_GEOGRAFICA values(110,'BUESACO',52);
insert into ZONA_GEOGRAFICA values(203,'COLON',52);
insert into ZONA_GEOGRAFICA values(207,'CONSACA',52);
insert into ZONA_GEOGRAFICA values(210,'CONTADERO',52);
insert into ZONA_GEOGRAFICA values(215,'CORDOBA',52);
insert into ZONA_GEOGRAFICA values(224,'CUASPUD',52);
insert into ZONA_GEOGRAFICA values(227,'CUMBAL',52);
insert into ZONA_GEOGRAFICA values(233,'CUMBITARA',52);
insert into ZONA_GEOGRAFICA values(240,'CHACHAGsI',52);
insert into ZONA_GEOGRAFICA values(250,'EL CHARCO',52);
insert into ZONA_GEOGRAFICA values(254,'EL PEÑOL',52);
insert into ZONA_GEOGRAFICA values(256,'EL ROSARIO',52);
insert into ZONA_GEOGRAFICA values(258,'EL TABLON DE GOMEZ',52);
insert into ZONA_GEOGRAFICA values(260,'EL TAMBO',52);
insert into ZONA_GEOGRAFICA values(287,'FUNES',52);
insert into ZONA_GEOGRAFICA values(317,'GUACHUCAL',52);
insert into ZONA_GEOGRAFICA values(320,'GUAITARILLA',52);
insert into ZONA_GEOGRAFICA values(323,'GUALMATAN',52);
insert into ZONA_GEOGRAFICA values(352,'ILES',52);
insert into ZONA_GEOGRAFICA values(354,'IMUES',52);
insert into ZONA_GEOGRAFICA values(356,'IPIALES',52);
insert into ZONA_GEOGRAFICA values(378,'LA CRUZ',52);
insert into ZONA_GEOGRAFICA values(381,'LA FLORIDA',52);
insert into ZONA_GEOGRAFICA values(385,'LA LLANADA',52);
insert into ZONA_GEOGRAFICA values(390,'LA TOLA',52);
insert into ZONA_GEOGRAFICA values(399,'LA UNION',52);
insert into ZONA_GEOGRAFICA values(405,'LEIVA',52);
insert into ZONA_GEOGRAFICA values(411,'LINARES',52);
insert into ZONA_GEOGRAFICA values(418,'LOS ANDES',52);
insert into ZONA_GEOGRAFICA values(427,'MAGsI',52);
insert into ZONA_GEOGRAFICA values(435,'MALLAMA',52);
insert into ZONA_GEOGRAFICA values(473,'MOSQUERA',52);
insert into ZONA_GEOGRAFICA values(480,'NARIÑO',52);
insert into ZONA_GEOGRAFICA values(490,'OLAYA HERRERA',52);
insert into ZONA_GEOGRAFICA values(506,'OSPINA',52);
insert into ZONA_GEOGRAFICA values(520,'FRANCISCO PIZARRO',52);
insert into ZONA_GEOGRAFICA values(540,'POLICARPA',52);
insert into ZONA_GEOGRAFICA values(560,'POTOSI',52);
insert into ZONA_GEOGRAFICA values(565,'PROVIDENCIA',52);
insert into ZONA_GEOGRAFICA values(573,'PUERRES',52);
insert into ZONA_GEOGRAFICA values(585,'PUPIALES',52);
insert into ZONA_GEOGRAFICA values(612,'RICAURTE',52);
insert into ZONA_GEOGRAFICA values(621,'ROBERTO PAYAN',52);
insert into ZONA_GEOGRAFICA values(678,'SAMANIEGO',52);
insert into ZONA_GEOGRAFICA values(683,'SANDONA',52);
insert into ZONA_GEOGRAFICA values(685,'SAN BERNARDO',52);
insert into ZONA_GEOGRAFICA values(687,'SAN LORENZO',52);
insert into ZONA_GEOGRAFICA values(693,'SAN PABLO',52);
insert into ZONA_GEOGRAFICA values(694,'SAN PEDRO DE CARTAGO',52);
insert into ZONA_GEOGRAFICA values(696,'SANTA BARBARA',52);
insert into ZONA_GEOGRAFICA values(699,'SANTACRUZ',52);
insert into ZONA_GEOGRAFICA values(720,'SAPUYES',52);
insert into ZONA_GEOGRAFICA values(786,'TAMINANGO',52);
insert into ZONA_GEOGRAFICA values(788,'TANGUA',52);
insert into ZONA_GEOGRAFICA values(835,'SAN ANDRES DE TUMACO',52);
insert into ZONA_GEOGRAFICA values(838,'TUQUERRES',52);
insert into ZONA_GEOGRAFICA values(885,'YACUANQUER',52);

insert into ZONA_GEOGRAFICA values(003,'ABREGO',54);
insert into ZONA_GEOGRAFICA values(051,'ARBOLEDAS',54);
insert into ZONA_GEOGRAFICA values(099,'BOCHALEMA',54);
insert into ZONA_GEOGRAFICA values(109,'BUCARASICA',54);
insert into ZONA_GEOGRAFICA values(125,'CACOTA',54);
insert into ZONA_GEOGRAFICA values(128,'CACHIRA',54);
insert into ZONA_GEOGRAFICA values(172,'CHINACOTA',54);
insert into ZONA_GEOGRAFICA values(174,'CHITAGA',54);
insert into ZONA_GEOGRAFICA values(206,'CONVENCION',54);
insert into ZONA_GEOGRAFICA values(223,'CUCUTILLA',54);
insert into ZONA_GEOGRAFICA values(239,'DURANIA',54);
insert into ZONA_GEOGRAFICA values(245,'EL CARMEN',54);
insert into ZONA_GEOGRAFICA values(250,'EL TARRA',54);
insert into ZONA_GEOGRAFICA values(261,'EL ZULIA',54);
insert into ZONA_GEOGRAFICA values(313,'GRAMALOTE',54);
insert into ZONA_GEOGRAFICA values(344,'HACARI',54);
insert into ZONA_GEOGRAFICA values(347,'HERRAN',54);
insert into ZONA_GEOGRAFICA values(377,'LABATECA',54);
insert into ZONA_GEOGRAFICA values(385,'LA ESPERANZA',54);
insert into ZONA_GEOGRAFICA values(398,'LA PLAYA',54);
insert into ZONA_GEOGRAFICA values(405,'LOS PATIOS',54);
insert into ZONA_GEOGRAFICA values(418,'LOURDES',54);
insert into ZONA_GEOGRAFICA values(480,'MUTISCUA',54);
insert into ZONA_GEOGRAFICA values(498,'OCAÑA',54);
insert into ZONA_GEOGRAFICA values(518,'PAMPLONA',54);
insert into ZONA_GEOGRAFICA values(520,'PAMPLONITA',54);
insert into ZONA_GEOGRAFICA values(553,'PUERTO SANTANDER',54);
insert into ZONA_GEOGRAFICA values(599,'RAGONVALIA',54);
insert into ZONA_GEOGRAFICA values(660,'SALAZAR',54);
insert into ZONA_GEOGRAFICA values(670,'SAN CALIXTO',54);
insert into ZONA_GEOGRAFICA values(673,'SAN CAYETANO',54);
insert into ZONA_GEOGRAFICA values(680,'SANTIAGO',54);
insert into ZONA_GEOGRAFICA values(720,'SARDINATA',54);
insert into ZONA_GEOGRAFICA values(743,'SILOS',54);
insert into ZONA_GEOGRAFICA values(800,'TEORAMA',54);
insert into ZONA_GEOGRAFICA values(810,'TIBU',54);
insert into ZONA_GEOGRAFICA values(820,'TOLEDO',54);
insert into ZONA_GEOGRAFICA values(871,'VILLA CARO',54);
insert into ZONA_GEOGRAFICA values(874,'VILLA DEL ROSARIO',54);

insert into ZONA_GEOGRAFICA values(111,'BUENAVISTA',63);
insert into ZONA_GEOGRAFICA values(130,'CALARCA',63);
insert into ZONA_GEOGRAFICA values(190,'CIRCASIA',63);
insert into ZONA_GEOGRAFICA values(212,'CORDOBA',63);
insert into ZONA_GEOGRAFICA values(272,'FILANDIA',63);
insert into ZONA_GEOGRAFICA values(302,'GENOVA',63);
insert into ZONA_GEOGRAFICA values(401,'LA TEBAIDA',63);
insert into ZONA_GEOGRAFICA values(470,'MONTENEGRO',63);
insert into ZONA_GEOGRAFICA values(548,'PIJAO',63);
insert into ZONA_GEOGRAFICA values(594,'QUIMBAYA',63);
insert into ZONA_GEOGRAFICA values(690,'SALENTO',63);

insert into ZONA_GEOGRAFICA values(045,'APIA',66);
insert into ZONA_GEOGRAFICA values(075,'BALBOA',66);
insert into ZONA_GEOGRAFICA values(088,'BELEN DE UMBRIA',66);
insert into ZONA_GEOGRAFICA values(170,'DOSQUEBRADAS',66);
insert into ZONA_GEOGRAFICA values(318,'GUATICA',66);
insert into ZONA_GEOGRAFICA values(383,'LA CELIA',66);
insert into ZONA_GEOGRAFICA values(400,'LA VIRGINIA',66);
insert into ZONA_GEOGRAFICA values(440,'MARSELLA',66);
insert into ZONA_GEOGRAFICA values(456,'MISTRATO',66);
insert into ZONA_GEOGRAFICA values(572,'PUEBLO RICO',66);
insert into ZONA_GEOGRAFICA values(594,'QUINCHIA',66);
insert into ZONA_GEOGRAFICA values(682,'SANTA ROSA DE CABAL',66);
insert into ZONA_GEOGRAFICA values(687,'SANTUARIO',66);

insert into ZONA_GEOGRAFICA values(013,'AGUADA',68);
insert into ZONA_GEOGRAFICA values(020,'ALBANIA',68);
insert into ZONA_GEOGRAFICA values(051,'ARATOCA',68);
insert into ZONA_GEOGRAFICA values(077,'BARBOSA',68);
insert into ZONA_GEOGRAFICA values(079,'BARICHARA',68);
insert into ZONA_GEOGRAFICA values(081,'BARRANCABERMEJA',68);
insert into ZONA_GEOGRAFICA values(092,'BETULIA',68);
insert into ZONA_GEOGRAFICA values(101,'BOLIVAR',68);
insert into ZONA_GEOGRAFICA values(121,'CABRERA',68);
insert into ZONA_GEOGRAFICA values(132,'CALIFORNIA',68);
insert into ZONA_GEOGRAFICA values(147,'CAPITANEJO',68);
insert into ZONA_GEOGRAFICA values(152,'CARCASI',68);
insert into ZONA_GEOGRAFICA values(160,'CEPITA',68);
insert into ZONA_GEOGRAFICA values(162,'CERRITO',68);
insert into ZONA_GEOGRAFICA values(167,'CHARALA',68);
insert into ZONA_GEOGRAFICA values(169,'CHARTA',68);
insert into ZONA_GEOGRAFICA values(176,'CHIMA',68);
insert into ZONA_GEOGRAFICA values(179,'CHIPATA',68);
insert into ZONA_GEOGRAFICA values(190,'CIMITARRA',68);
insert into ZONA_GEOGRAFICA values(207,'CONCEPCION',68);
insert into ZONA_GEOGRAFICA values(209,'CONFINES',68);
insert into ZONA_GEOGRAFICA values(211,'CONTRATACION',68);
insert into ZONA_GEOGRAFICA values(217,'COROMORO',68);
insert into ZONA_GEOGRAFICA values(229,'CURITI',68);
insert into ZONA_GEOGRAFICA values(235,'EL CARMEN DE CHUCURI',68);
insert into ZONA_GEOGRAFICA values(245,'EL GUACAMAYO',68);
insert into ZONA_GEOGRAFICA values(250,'EL PEÑON',68);
insert into ZONA_GEOGRAFICA values(255,'EL PLAYON',68);
insert into ZONA_GEOGRAFICA values(264,'ENCINO',68);
insert into ZONA_GEOGRAFICA values(266,'ENCISO',68);
insert into ZONA_GEOGRAFICA values(271,'FLORIAN',68);
insert into ZONA_GEOGRAFICA values(276,'FLORIDABLANCA',68);
insert into ZONA_GEOGRAFICA values(296,'GALAN',68);
insert into ZONA_GEOGRAFICA values(298,'GAMBITA',68);
insert into ZONA_GEOGRAFICA values(307,'GIRON',68);
insert into ZONA_GEOGRAFICA values(318,'GUACA',68);
insert into ZONA_GEOGRAFICA values(320,'GUADALUPE',68);
insert into ZONA_GEOGRAFICA values(322,'GUAPOTA',68);
insert into ZONA_GEOGRAFICA values(324,'GUAVATA',68);
insert into ZONA_GEOGRAFICA values(327,'GsEPSA',68);
insert into ZONA_GEOGRAFICA values(344,'HATO',68);
insert into ZONA_GEOGRAFICA values(368,'JESUS MARIA',68);
insert into ZONA_GEOGRAFICA values(370,'JORDAN',68);
insert into ZONA_GEOGRAFICA values(377,'LA BELLEZA',68);
insert into ZONA_GEOGRAFICA values(385,'LANDAZURI',68);
insert into ZONA_GEOGRAFICA values(397,'LA PAZ',68);
insert into ZONA_GEOGRAFICA values(406,'LEBRIJA',68);
insert into ZONA_GEOGRAFICA values(418,'LOS SANTOS',68);
insert into ZONA_GEOGRAFICA values(425,'MACARAVITA',68);
insert into ZONA_GEOGRAFICA values(432,'MALAGA',68);
insert into ZONA_GEOGRAFICA values(444,'MATANZA',68);
insert into ZONA_GEOGRAFICA values(464,'MOGOTES',68);
insert into ZONA_GEOGRAFICA values(468,'MOLAGAVITA',68);
insert into ZONA_GEOGRAFICA values(498,'OCAMONTE',68);
insert into ZONA_GEOGRAFICA values(500,'OIBA',68);
insert into ZONA_GEOGRAFICA values(502,'ONZAGA',68);
insert into ZONA_GEOGRAFICA values(522,'PALMAR',68);
insert into ZONA_GEOGRAFICA values(524,'PALMAS DEL SOCORRO',68);
insert into ZONA_GEOGRAFICA values(533,'PARAMO',68);
insert into ZONA_GEOGRAFICA values(547,'PIEDECUESTA',68);
insert into ZONA_GEOGRAFICA values(549,'PINCHOTE',68);
insert into ZONA_GEOGRAFICA values(572,'PUENTE NACIONAL',68);
insert into ZONA_GEOGRAFICA values(573,'PUERTO PARRA',68);
insert into ZONA_GEOGRAFICA values(575,'PUERTO WILCHES',68);
insert into ZONA_GEOGRAFICA values(615,'RIONEGRO',68);
insert into ZONA_GEOGRAFICA values(655,'SABANA DE TORRES',68);
insert into ZONA_GEOGRAFICA values(669,'SAN ANDRES',68);
insert into ZONA_GEOGRAFICA values(673,'SAN BENITO',68);
insert into ZONA_GEOGRAFICA values(679,'SAN GIL',68);
insert into ZONA_GEOGRAFICA values(682,'SAN JOAQUIN',68);
insert into ZONA_GEOGRAFICA values(684,'SAN JOSE DE MIRANDA',68);
insert into ZONA_GEOGRAFICA values(686,'SAN MIGUEL',68);
insert into ZONA_GEOGRAFICA values(689,'SAN VICENTE DE CHUCURI',68);
insert into ZONA_GEOGRAFICA values(705,'SANTA BARBARA',68);
insert into ZONA_GEOGRAFICA values(720,'SANTA HELENA DEL OPON',68);
insert into ZONA_GEOGRAFICA values(745,'SIMACOTA',68);
insert into ZONA_GEOGRAFICA values(755,'SOCORRO',68);
insert into ZONA_GEOGRAFICA values(770,'SUAITA',68);
insert into ZONA_GEOGRAFICA values(773,'SUCRE',68);
insert into ZONA_GEOGRAFICA values(780,'SURATA',68);
insert into ZONA_GEOGRAFICA values(820,'TONA',68);
insert into ZONA_GEOGRAFICA values(855,'VALLE DE SAN JOSE',68);
insert into ZONA_GEOGRAFICA values(861,'VELEZ',68);
insert into ZONA_GEOGRAFICA values(867,'VETAS',68);
insert into ZONA_GEOGRAFICA values(872,'VILLANUEVA',68);
insert into ZONA_GEOGRAFICA values(895,'ZAPATOCA',68);

insert into ZONA_GEOGRAFICA values(110,'BUENAVISTA',70);
insert into ZONA_GEOGRAFICA values(124,'CAIMITO',70);
insert into ZONA_GEOGRAFICA values(204,'COLOSO',70);
insert into ZONA_GEOGRAFICA values(215,'COROZAL',70);
insert into ZONA_GEOGRAFICA values(221,'COVEÑAS',70);
insert into ZONA_GEOGRAFICA values(230,'CHALAN',70);
insert into ZONA_GEOGRAFICA values(233,'EL ROBLE',70);
insert into ZONA_GEOGRAFICA values(235,'GALERAS',70);
insert into ZONA_GEOGRAFICA values(265,'GUARANDA',70);
insert into ZONA_GEOGRAFICA values(400,'LA UNION',70);
insert into ZONA_GEOGRAFICA values(418,'LOS PALMITOS',70);
insert into ZONA_GEOGRAFICA values(429,'MAJAGUAL',70);
insert into ZONA_GEOGRAFICA values(473,'MORROA',70);
insert into ZONA_GEOGRAFICA values(508,'OVEJAS',70);
insert into ZONA_GEOGRAFICA values(523,'PALMITO',70);
insert into ZONA_GEOGRAFICA values(670,'SAMPUES',70);
insert into ZONA_GEOGRAFICA values(678,'SAN BENITO ABAD',70);
insert into ZONA_GEOGRAFICA values(702,'SAN JUAN DE BETULIA',70);
insert into ZONA_GEOGRAFICA values(708,'SAN MARCOS',70);
insert into ZONA_GEOGRAFICA values(713,'SAN ONOFRE',70);
insert into ZONA_GEOGRAFICA values(717,'SAN PEDRO',70);
insert into ZONA_GEOGRAFICA values(742,'SAN LUIS DE SINCE',70);
insert into ZONA_GEOGRAFICA values(771,'SUCRE',70);
insert into ZONA_GEOGRAFICA values(820,'SANTIAGO DE TOLU',70);
insert into ZONA_GEOGRAFICA values(823,'TOLU VIEJO',70);

insert into ZONA_GEOGRAFICA values(024,'ALPUJARRA',73);
insert into ZONA_GEOGRAFICA values(026,'ALVARADO',73);
insert into ZONA_GEOGRAFICA values(030,'AMBALEMA',73);
insert into ZONA_GEOGRAFICA values(043,'ANZOATEGUI',73);
insert into ZONA_GEOGRAFICA values(055,'ARMERO',73);
insert into ZONA_GEOGRAFICA values(067,'ATACO',73);
insert into ZONA_GEOGRAFICA values(124,'CAJAMARCA',73);
insert into ZONA_GEOGRAFICA values(148,'CARMEN DE APICALA',73);
insert into ZONA_GEOGRAFICA values(152,'CASABIANCA',73);
insert into ZONA_GEOGRAFICA values(168,'CHAPARRAL',73);
insert into ZONA_GEOGRAFICA values(200,'COELLO',73);
insert into ZONA_GEOGRAFICA values(217,'COYAIMA',73);
insert into ZONA_GEOGRAFICA values(226,'CUNDAY',73);
insert into ZONA_GEOGRAFICA values(236,'DOLORES',73);
insert into ZONA_GEOGRAFICA values(268,'ESPINAL',73);
insert into ZONA_GEOGRAFICA values(270,'FALAN',73);
insert into ZONA_GEOGRAFICA values(275,'FLANDES',73);
insert into ZONA_GEOGRAFICA values(283,'FRESNO',73);
insert into ZONA_GEOGRAFICA values(319,'GUAMO',73);
insert into ZONA_GEOGRAFICA values(347,'HERVEO',73);
insert into ZONA_GEOGRAFICA values(349,'HONDA',73);
insert into ZONA_GEOGRAFICA values(352,'ICONONZO',73);
insert into ZONA_GEOGRAFICA values(408,'LERIDA',73);
insert into ZONA_GEOGRAFICA values(411,'LIBANO',73);
insert into ZONA_GEOGRAFICA values(443,'MARIQUITA',73);
insert into ZONA_GEOGRAFICA values(449,'MELGAR',73);
insert into ZONA_GEOGRAFICA values(461,'MURILLO',73);
insert into ZONA_GEOGRAFICA values(483,'NATAGAIMA',73);
insert into ZONA_GEOGRAFICA values(504,'ORTEGA',73);
insert into ZONA_GEOGRAFICA values(520,'PALOCABILDO',73);
insert into ZONA_GEOGRAFICA values(547,'PIEDRAS',73);
insert into ZONA_GEOGRAFICA values(555,'PLANADAS',73);
insert into ZONA_GEOGRAFICA values(563,'PRADO',73);
insert into ZONA_GEOGRAFICA values(585,'PURIFICACION',73);
insert into ZONA_GEOGRAFICA values(616,'RIOBLANCO',73);
insert into ZONA_GEOGRAFICA values(622,'RONCESVALLES',73);
insert into ZONA_GEOGRAFICA values(624,'ROVIRA',73);
insert into ZONA_GEOGRAFICA values(671,'SALDAÑA',73);
insert into ZONA_GEOGRAFICA values(675,'SAN ANTONIO',73);
insert into ZONA_GEOGRAFICA values(678,'SAN LUIS',73);
insert into ZONA_GEOGRAFICA values(686,'SANTA ISABEL',73);
insert into ZONA_GEOGRAFICA values(770,'SUAREZ',73);
insert into ZONA_GEOGRAFICA values(854,'VALLE DE SAN JUAN',73);
insert into ZONA_GEOGRAFICA values(861,'VENADILLO',73);
insert into ZONA_GEOGRAFICA values(870,'VILLAHERMOSA',73);
insert into ZONA_GEOGRAFICA values(873,'VILLARRICA',73);

insert into ZONA_GEOGRAFICA values(020,'ALCALA',76);
insert into ZONA_GEOGRAFICA values(036,'ANDALUCIA',76);
insert into ZONA_GEOGRAFICA values(041,'ANSERMANUEVO',76);
insert into ZONA_GEOGRAFICA values(054,'ARGELIA',76);
insert into ZONA_GEOGRAFICA values(100,'BOLIVAR',76);
insert into ZONA_GEOGRAFICA values(109,'BUENAVENTURA',76);
insert into ZONA_GEOGRAFICA values(111,'GUADALAJARA DE BUGA',76);
insert into ZONA_GEOGRAFICA values(113,'BUGALAGRANDE',76);
insert into ZONA_GEOGRAFICA values(122,'CAICEDONIA',76);
insert into ZONA_GEOGRAFICA values(126,'CALIMA',76);
insert into ZONA_GEOGRAFICA values(130,'CANDELARIA',76);
insert into ZONA_GEOGRAFICA values(147,'CARTAGO',76);
insert into ZONA_GEOGRAFICA values(233,'DAGUA',76);
insert into ZONA_GEOGRAFICA values(243,'EL AGUILA',76);
insert into ZONA_GEOGRAFICA values(246,'EL CAIRO',76);
insert into ZONA_GEOGRAFICA values(248,'EL CERRITO',76);
insert into ZONA_GEOGRAFICA values(250,'EL DOVIO',76);
insert into ZONA_GEOGRAFICA values(275,'FLORIDA',76);
insert into ZONA_GEOGRAFICA values(306,'GINEBRA',76);
insert into ZONA_GEOGRAFICA values(318,'GUACARI',76);
insert into ZONA_GEOGRAFICA values(364,'JAMUNDI',76);
insert into ZONA_GEOGRAFICA values(377,'LA CUMBRE',76);
insert into ZONA_GEOGRAFICA values(400,'LA UNION',76);
insert into ZONA_GEOGRAFICA values(403,'LA VICTORIA',76);
insert into ZONA_GEOGRAFICA values(497,'OBANDO',76);
insert into ZONA_GEOGRAFICA values(520,'PALMIRA',76);
insert into ZONA_GEOGRAFICA values(563,'PRADERA',76);
insert into ZONA_GEOGRAFICA values(606,'RESTREPO',76);
insert into ZONA_GEOGRAFICA values(616,'RIOFRIO',76);
insert into ZONA_GEOGRAFICA values(622,'ROLDANILLO',76);
insert into ZONA_GEOGRAFICA values(670,'SAN PEDRO',76);
insert into ZONA_GEOGRAFICA values(736,'SEVILLA',76);
insert into ZONA_GEOGRAFICA values(823,'TORO',76);
insert into ZONA_GEOGRAFICA values(828,'TRUJILLO',76);
insert into ZONA_GEOGRAFICA values(834,'TULUA',76);
insert into ZONA_GEOGRAFICA values(845,'ULLOA',76);
insert into ZONA_GEOGRAFICA values(863,'VERSALLES',76);
insert into ZONA_GEOGRAFICA values(869,'VIJES',76);
insert into ZONA_GEOGRAFICA values(890,'YOTOCO',76);
insert into ZONA_GEOGRAFICA values(892,'YUMBO',76);
insert into ZONA_GEOGRAFICA values(895,'ZARZAL',76);

insert into ZONA_GEOGRAFICA values(065,'ARAUQUITA',81);
insert into ZONA_GEOGRAFICA values(220,'CRAVO NORTE',81);
insert into ZONA_GEOGRAFICA values(300,'FORTUL',81);
insert into ZONA_GEOGRAFICA values(591,'PUERTO RONDON',81);
insert into ZONA_GEOGRAFICA values(736,'SARAVENA',81);
insert into ZONA_GEOGRAFICA values(794,'TAME',81);

insert into ZONA_GEOGRAFICA values(010,'AGUAZUL',85);
insert into ZONA_GEOGRAFICA values(015,'CHAMEZA',85);
insert into ZONA_GEOGRAFICA values(125,'HATO COROZAL',85);
insert into ZONA_GEOGRAFICA values(136,'LA SALINA',85);
insert into ZONA_GEOGRAFICA values(139,'MANI',85);
insert into ZONA_GEOGRAFICA values(162,'MONTERREY',85);
insert into ZONA_GEOGRAFICA values(225,'NUNCHIA',85);
insert into ZONA_GEOGRAFICA values(230,'OROCUE',85);
insert into ZONA_GEOGRAFICA values(250,'PAZ DE ARIPORO',85);
insert into ZONA_GEOGRAFICA values(263,'PORE',85);
insert into ZONA_GEOGRAFICA values(279,'RECETOR',85);
insert into ZONA_GEOGRAFICA values(300,'SABANALARGA',85);
insert into ZONA_GEOGRAFICA values(315,'SACAMA',85);
insert into ZONA_GEOGRAFICA values(325,'SAN LUIS DE PALENQUE',85);
insert into ZONA_GEOGRAFICA values(400,'TAMARA',85);
insert into ZONA_GEOGRAFICA values(410,'TAURAMENA',85);
insert into ZONA_GEOGRAFICA values(430,'TRINIDAD',85);
insert into ZONA_GEOGRAFICA values(440,'VILLANUEVA',85);

insert into ZONA_GEOGRAFICA values(219,'COLON',86);
insert into ZONA_GEOGRAFICA values(320,'ORITO',86);
insert into ZONA_GEOGRAFICA values(568,'PUERTO ASIS',86);
insert into ZONA_GEOGRAFICA values(569,'PUERTO CAICEDO',86);
insert into ZONA_GEOGRAFICA values(571,'PUERTO GUZMAN',86);
insert into ZONA_GEOGRAFICA values(573,'LEGUIZAMO',86);
insert into ZONA_GEOGRAFICA values(749,'SIBUNDOY',86);
insert into ZONA_GEOGRAFICA values(755,'SAN FRANCISCO',86);
insert into ZONA_GEOGRAFICA values(757,'SAN MIGUEL',86);
insert into ZONA_GEOGRAFICA values(760,'SANTIAGO',86);
insert into ZONA_GEOGRAFICA values(865,'VALLE DEL GUAMUEZ',86);
insert into ZONA_GEOGRAFICA values(885,'VILLAGARZON',86);

insert into ZONA_GEOGRAFICA values(564,'PROVIDENCIA',88);
insert into ZONA_GEOGRAFICA values(001,'LETICIA',91);
insert into ZONA_GEOGRAFICA values(263,'EL ENCANTO',91);
insert into ZONA_GEOGRAFICA values(405,'LA CHORRERA',91);
insert into ZONA_GEOGRAFICA values(407,'LA PEDRERA',91);
insert into ZONA_GEOGRAFICA values(430,'LA VICTORIA',91);
insert into ZONA_GEOGRAFICA values(460,'MIRITI - PARANA',91);
insert into ZONA_GEOGRAFICA values(530,'PUERTO ALEGRIA',91);
insert into ZONA_GEOGRAFICA values(536,'PUERTO ARICA',91);
insert into ZONA_GEOGRAFICA values(540,'PUERTO NARIÑO',91);
insert into ZONA_GEOGRAFICA values(669,'PUERTO SANTANDER',91);
insert into ZONA_GEOGRAFICA values(798,'TARAPACA',91);

insert into ZONA_GEOGRAFICA values(343,'BARRANCO MINAS',94);
insert into ZONA_GEOGRAFICA values(663,'MAPIRIPANA',94);
insert into ZONA_GEOGRAFICA values(883,'SAN FELIPE',94);
insert into ZONA_GEOGRAFICA values(884,'PUERTO COLOMBIA',94);
insert into ZONA_GEOGRAFICA values(885,'LA GUADALUPE',94);
insert into ZONA_GEOGRAFICA values(886,'CACAHUAL',94);
insert into ZONA_GEOGRAFICA values(887,'PANA PANA',94);
insert into ZONA_GEOGRAFICA values(888,'MORICHAL',94);
insert into ZONA_GEOGRAFICA values(001,'SAN JOSE DEL GUAVIARE',95);
insert into ZONA_GEOGRAFICA values(015,'CALAMAR',95);
insert into ZONA_GEOGRAFICA values(025,'EL RETORNO',95);
insert into ZONA_GEOGRAFICA values(200,'MIRAFLORES',95);

insert into ZONA_GEOGRAFICA values(161,'CARURU',97);
insert into ZONA_GEOGRAFICA values(511,'PACOA',97);
insert into ZONA_GEOGRAFICA values(666,'TARAIRA',97);
insert into ZONA_GEOGRAFICA values(777,'PAPUNAUA',97);
insert into ZONA_GEOGRAFICA values(889,'YAVARATE',97);

insert into ZONA_GEOGRAFICA values(524,'LA PRIMAVERA',99);
insert into ZONA_GEOGRAFICA values(624,'SANTA ROSALIA',99);
insert into ZONA_GEOGRAFICA values(773,'CUMARIBO',99);
commit;

